version: '3.3'

services:

  db: # Container do mysql
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/mysql_db.env
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    port: 
      - "8000:80"
    restart: always
    env_file:
      - ./config/wordpress_db.env
    networks:
      - backend

volumes:
  db_data: {}
networks:
  backend:
    driver: bridge